services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: maven:3.6.3-openjdk-17
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    networks:
      - dir_music_network

networks:
    dir_music_network:
        driver: bridge
        external: true
